### ISSUE TITLE
QR tidak muncul

### ISSUE THREAD

**Issue by abdulaziz1999** [ngekoding/whatsapp-api-tutorial#107]

**Comment by abdulaziz1999** [comment]
pas di cek  do broser qrcodenya gk muncul

**Comment by ngekoding** [comment]
Pastikan sudah melakukan instalasi library yang dibutuhkan. Jika merujuk ke repository ini, silahkan jalankan `npm install`.

Dan karena adanya pembaruan berkala pda library whatsapp-web.js, pastikan sudah menggunakan versi terbaru, jalankan `npm update` jika diperlukan.

**Comment by harrymaulana** [comment]
saya menemukan problem yang sama, penyelesainnya gmna @abdulaziz1999  ? saya sudah melakukan npm install dan npm update
@ngekoding

**Comment by diazzaid** [comment]
> ketika dijalankan npm run start:dev
> 
> > whatsapp-api@1.0.0 start:dev
> > nodemon app.js
> 
> [nodemon] 2.0.12 [nodemon] to restart at any time, enter `rs` [nodemon] watching path(s): _._ [nodemon] watching extensions: js,mjs,json [nodemon] starting `node app.js` App running on *: 8000 (node:65490) UnhandledPromiseRejectionWarning: Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (901912). at ChromeLauncher.launch (/home/dqakses/App/whatsapp-api-tutorial-master/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:88:27) at async Client.initialize (/home/dqakses/App/whatsapp-api-tutorial-master/node_modules/whatsapp-web.js/src/Client.js:74:23) (Use `node --trace-warnings ...` to show where the warning was created) (node:65490) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:65490) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. Express-file-upload: Request is not eligible for file upload! Express-file-upload: Request is not eligible for file upload!

biasana setelah di update socket.io nya berubah sedangkan di kodingan index.html menggunakan versi 2.3.0.
jadi pastikan socket.io pada index.html dan module yang terinstall versinya sama..

**Comment by destiaarti** [comment]
![Screen Shot 2021-11-02 at 15 55 43](https://user-images.githubusercontent.com/54435481/139815875-e1c99896-26b8-4c52-a53a-c326c2a03eb5.png)
saya uda npm install updet sm cek versinya mas @ngekoding , tp masi begini

**Comment by destiaarti** [comment]
di local aman, pas dihosting aja begitu, apa ada yg slh kah? callbacknya ato apa nya kah? smpe qr nya ngga muncul

**Comment by ngekoding** [comment]
Coba liat di console mas, biasanya ada errornya.

**Comment by destiaarti** [comment]
console nya ngga ada error sm skli mas. Dan aku gatau knp ya mas @ngekoding itu kan aku taruh subdomain. hbs ngerun itu domain utamanya mlh down jd 503 gitu. Kayanya ngga ggara portnya , karena yg satu dy php gitu mas, sedangkan ini node js beda port biasanya. kenapa ya mas @ngekoding ?

**Comment by destiaarti** [comment]
```
(node:2073584) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/edukasis/nodevenv/wa1.edukasisahamsyariah.id/10/lib/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/xx/nodevenv/xx/10/lib/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
    at Interface.helper_js_1.helper.addEventListener (/home/xx/nodevenv/xx/10/lib/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:187:68)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:2073584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2073584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
oh ya sblmnya ada begituan mas, cmn di console nya ngga error

**Comment by destiaarti** [comment]
itu aku dpt dr stdr_log nya bukan dr console/terminal

**Comment by ngekoding** [comment]
Jadi kan ini pakai library whatsapp-web.js yang notabene memerlupan Puppeteer, nah Puppeteer itu sendiri butub lib tertentu untuk bisa jalan.

Kasus ini biasanya saya temui di OS Linux, contohnya dari pesan error di atas mengatakan bahwa dia gak bisa menemuka lib **libatk-bridge-2.0.so.0**, jadi harus diinstall dulu.

**Comment by destiaarti** [comment]
hmm kalo gitu hrs nya ckup npm install/update dah cukup kan ya mas @ngekoding ? apa hrs install si lib itu kepisah npm nya?

**Comment by ngekoding** [comment]
Bukan bukan, itu library dari sisi OSnya, bukan npm. Jadi installnya semacam `apt-get install libnya`

**Comment by aanmochtar80** [comment]
maaf min saya juga sampai sekarang masih mengalami hal yang sama cuman sampai disini saja 

`root@whatsapp:~/whatsapp# npm run start:dev

> whatsapp-api@1.0.0 start:dev
> nodemon app.js

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
App running on *: 8000
`

mohon pencerahannya min

**Comment by ngekoding** [comment]
@aanmochtar80 Dicoba untuk melakukan update library terlebih dulu, jalankan `npm update`

**Comment by mofris** [comment]
bang kasus gua kaya gitu, QR nya ga muncul pas di hosting. gimana tuh bang biar solved?

**Comment by mofris** [comment]
> libatk-bridge-2.0.so.0

tutorial bang

**Comment by ngekoding** [comment]
> bang kasus gua kaya gitu, QR nya ga muncul pas di hosting. gimana tuh bang biar solved?

Library whatsapp-web.js memang tidak bisa dijalankan pada shared hosting, karena ia membutuhkan Puppeteer, minimal VPS.

**Comment by mofris** [comment]
saya sudah pake VPS tetap seperti itu bang, mohon bantuannya

**Comment by nian88** [comment]
> 
sudo apt install libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon-x11-0 libgtk-3-0 libgbm1 libasound2

**Comment by fredwanderley** [comment]
I have the same problem, I can't load the Qrcode in the browser, after starting npm the return is:
Express-file-upload: Request is not eligible for file upload!
