### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by ibnudirsan** [ngekoding/whatsapp-api-tutorial#132]
Assalamu;alaikum...
apakah terjadi update an WhatsApp pengarui dengan API WA ini ?.
ada error seperti ini :

`(node:37928) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at __puppeteer_evaluation_script__:36:78
    at ExecutionContext._evaluateInternal (D:\RumahDev\server-wa\nov\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (D:\RumahDev\server-wa\nov\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.initialize (D:\RumahDev\server-wa\nov\node_modules\whatsapp-web.js\src\Client.js:172:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:37928) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector `canvas` failed: timeout 45000ms exceeded
    at new WaitTask (D:\RumahDev\server-wa\nov\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:513:34)
    at DOMWorld.waitForSelectorInPage (D:\RumahDev\server-wa\nov\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:424:26)
    at Object.internalHandler.waitFor (D:\RumahDev\server-wa\nov\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (D:\RumahDev\server-wa\nov\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:317:29)
    at Frame.waitForSelector (D:\RumahDev\server-wa\nov\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:841:51)
    at Page.waitForSelector (D:\RumahDev\server-wa\nov\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:2313:33)
    at Timeout.getQrCode (D:\RumahDev\server-wa\nov\node_modules\whatsapp-web.js\src\Client.js:143:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:37928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)`

Mohon bantuannya.
terimakasih.

**Comment by ngekoding** [comment]
Wa'alaikumussalam

Seingat saya sudah pernah ada yang bahas/menanyakan di issue whatsapp-web.js

Silahkan tambahkan catch seperti kode berikut ini.

```js
client.initialize().catch(err => {
  console.log(err);
});
```

**Comment by ibnudirsan** [comment]
jazakallah khair, akhy...
sudah solved untuk saat ini..
sedang di uji coba oleh Team..
mohon keridhoan nya,
aplikasi antum di pakai oleh Team Kami..
Badan Wakaf Al-Quran..

**Comment by ngekoding** [comment]
Wa anta fajazaakallahu khairan.
Alhamdulillah jika bisa bermanfaat, apalagi untuk kepentingan Islam. 

Baarakallahu fiikum.
