### ISSUE TITLE
Pada saat di Scan langsung error

### ISSUE THREAD

**Issue by faiz5758** [ngekoding/whatsapp-api-tutorial#141]
Error: Protocol error (Runtime.callFunctionOn): Target closed.

Lengkapnya seperti ini

C:\wa\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:217
            this._callbacks.set(id, { resolve, reject, error: new Error(), method });
                                                              ^

Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at C:\wa\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:217:63
    at new Promise (<anonymous>)
    at CDPSession.send (C:\wa\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:216:16)
    at ExecutionContext._evaluateInternal (C:\wa\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluateHandle (C:\wa\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:155:21)
    at WaitTask.rerun (C:\wa\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:536:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by ngekoding** [comment]
Apakah menggunakan Whatsapp Multi Device Beta?

**Comment by faiz5758** [comment]
> Apakah menggunakan Whatsapp Multi Device Beta?

Tidak

**Comment by ngekoding** [comment]
Pastikan menggunakan whatsapp-web.js versi terbaru.
