### ISSUE TITLE
reading 'WidFactory'

### ISSUE THREAD

**Issue by gotopa** [ngekoding/whatsapp-api-tutorial#152]
Salam
kalo error seperti ini kenapa ya ?
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')
    at __puppeteer_evaluation_script__:2:42
    at ExecutionContext._evaluateInternal (/var/www/html/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
    at async ExecutionContext.evaluate (/var/www/html//node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.sendMessage (/opt/lampp/htdocs/esqwa/ww/node_modules/whatsapp-web.js/src/Client.js:556:28)
    
terkadang seperti itu

**Comment by arnoldjulianto** [comment]
tunggu sampe whatsapp is ready mas
