### ISSUE TITLE
 no such file or directory, open './whatsapp-session.json'

### ISSUE THREAD

**Issue by Marzuki5** [ngekoding/whatsapp-api-tutorial#16]
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open './whatsapp-session.json'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at getSessionsFile (D:\wasem\app-multiple-device.js:38:24)
    at init (D:\wasem\app-multiple-device.js:142:25)
    at Object.<anonymous> (D:\wasem\app-multiple-device.js:155:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: './whatsapp-session.json'
}

**Comment by ngekoding** [comment]
Silahkan merujuk kesini https://github.com/ngekoding/whatsapp-api-tutorial/issues/15
