### ISSUE TITLE
client.destroy() throws error

### ISSUE THREAD

**Issue by venki1410** [ngekoding/whatsapp-api-tutorial#178]
**this is my disconnected event**

`client.on('disconnected',(reason)=>{
    io.emit('message',{id:id,text:"mobile Logged out !"});
    fs.unlinkSync(SESSION_FILE_PATH,function(err){
        if(err) return console.log(err);
        console.log('session file destroyed');
    });
    client.destroy();
    client.initialize();
});`

**when the user logged out it will throw puppeteer error like**

_/Users/venkat/project/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:189
                throw new Error(${PROCESS_ERROR_EXPLANATION}\nError cause: ${error.stack});
                      ^

Error: Puppeteer was unable to kill the process which ran the browser binary.
This means that, on future Puppeteer launches, Puppeteer might not be able to launch the browser.
Please check your open processes and ensure that the browser processes that Puppeteer launched have been killed.
If you think this is a bug, please report it on the Puppeteer issue tracker.
Error cause: Error: kill EPERM
    at process.kill (node:internal/process/per_thread:220:13)
    at BrowserRunner.kill (/Users/venkat/project/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:29)
    at BrowserRunner.close (/Users/venkat/project/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:158:18)
    at Browser.close (/Users/venkat/project/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:394:35)
    at Client.destroy (/Users/venkat/project/node_modules/whatsapp-web.js/src/Client.js:478:31)
    at /Users/venkat/project/node_modules/whatsapp-web.js/src/Client.js:469:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BrowserRunner.kill (/Users/venkat/project/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:189:23)
    at BrowserRunner.close (/Users/venkat/project/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:158:18)
    at Browser.close (/Users/venkat/project/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:394:35)
    at Client.destroy (/Users/venkat/project/node_modules/whatsapp-web.js/src/Client.js:478:31)
    at /Users/venkat/project/node_modules/whatsapp-web.js/src/Client.js:469:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`_

**specifications**
 node-v16.14.0
 whatsapp-web.js - ^1.16.4
 os - MAC

**Comment by huiralb** [comment]
Hai @venki1410  Please update whatsapp-web.js to 1.16.5
