### ISSUE TITLE
Not Working After npm update

### ISSUE THREAD

**Issue by QomariSanjaya** [ngekoding/whatsapp-api-tutorial#205]
Saya mengedit file app.js, setelah disimpan, sebagaimana semestinya app akan otomatis merestart, tapi setelah itu app tidak merespon pesan auto reply, jadi saya melakukan command `npm udpate` dan muncul seperti ini

```
up to date, audited 315 packages in 10s

30 packages are looking for funding
  run `npm fund` for details

7 vulnerabilities (2 moderate, 3 high, 2 critical)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

Maka saya lakukan `npm audit fix --force`
Sebelumnya beberapa kali saya melakukan hal yang sama, dan setelah app di run berjalan dengan normal, tapi kali ini app tidak merespon pesan auto reply, tidak ada pesan error di terminal

**Comment by QomariSanjaya** [comment]
Setelah coba dijalankan selama beberapa menit, akhirnya muncul pesan error seperti ini:

`(node:2314) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'QueryExist')
    at __puppeteer_evaluation_script__:2:47
    at ExecutionContext._evaluateInternal (/home/wabot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/home/wabot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.getNumberId (/home/wabot/node_modules/whatsapp-web.js/src/Client.js:945:16)
    at async Client.isRegisteredUser (/home/wabot/node_modules/whatsapp-web.js/src/Client.js:931:24)
    at async checkRegisteredNumber (/home/wabot/app.js:169:24)
    at async /home/wabot/app.js:194:30
(node:2314) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2314) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Saya gak paham apa maksudnya, masih awam, tolong dibantu

**Comment by cula09** [comment]
itu library puppeteernya belum keinstall, sama seperti saya setelah update error puppeteer.
cukup jalankan command **npm i puppeteer**
