### ISSUE TITLE
Logs: Connecting....

### ISSUE THREAD

**Issue by ccmks** [ngekoding/whatsapp-api-tutorial#215]
![image](https://user-images.githubusercontent.com/49300986/177307217-b44e2ba6-f194-4dcc-862a-396d2870ff62.png)

Saya menggunakan WA multi device, dan salah satunya menunjukan connecting.... sedangkan lainnya sudah authenticated. Apa yang terjadi dengan ini dan bagaimana saya bisa lihat lognya yang lebih detail?

Terima kasih

**Comment by ngekoding** [comment]
Silakan lihat pada terminal, biasanya pesan itu ketika masih loading.

**Comment by ccmks** [comment]
Sudah install PM2 jd tdk kelihatan d terminal

**Comment by ngekoding** [comment]
Coba ini mas https://pm2.keymetrics.io/docs/usage/log-management/

**Comment by aangwie** [comment]
@ngekoding Om di vps saya jalankan lancar, baru kemarin dapet error kaya gini.

Error: Evaluation failed: TypeError: e.isLid is not a function
    at Object.t.queryExists [as QueryExist] (https://web.whatsapp.com/bootstrap_qr.2c01e0e4abde696b6ff5.js:50:120627)
    at __puppeteer_evaluation_script__:2:47
    at ExecutionContext._evaluateInternal (/home/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.getNumberId (/home/wa/node_modules/whatsapp-web.js/src/Client.js:951:16)
    at async Client.isRegisteredUser (/home/wa/node_modules/whatsapp-web.js/src/Client.js:937:24)
    at async checkRegisteredNumber (/home/wa/app.js:151:24)
    at async /home/wa/app.js:176:30

jadi saat dijalankan tidak bisa mengirim pesan... solusinya bagaimana om?

**Comment by ngekoding** [comment]
Silakan cek issue yang saya pin, sudah dibahas.
