### ISSUE TITLE
Error saat mengirim pesan

### ISSUE THREAD

**Issue by rudipratm** [ngekoding/whatsapp-api-tutorial#216]
Salam gan, sebelumnya (sejak 2 hari lalu) saya gunakan normal saja tapi pagi ini saat mau kirimkan pesan verifikasi malah muncul pesan error:
### [**Link Pastebin**](https://pastebin.com/mjS2e3Gn)
Semoga dapat dibantu.

**Comment by ngekoding** [comment]
Silakan dicoba untuk update library-nya dulu, jalankan `npm update whatsapp-web.js`

**Comment by rudipratm** [comment]
Barusan saya coba, tapi error yang sama tetap muncul.

```
/srv/node/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'QueryExist')
    at __puppeteer_evaluation_script__:2:47
    at ExecutionContext._evaluateInternal (/srv/node/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/srv/node/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.getNumberId (/srv/node/whatsapp-api/node_modules/whatsapp-web.js/src/Client.js:951:16)
    at async Client.isRegisteredUser (/srv/node/whatsapp-api/node_modules/whatsapp-web.js/src/Client.js:937:24)
    at async checkRegisteredNumber (/srv/node/whatsapp-api/app.js:151:24)
    at async /srv/node/whatsapp-api/app.js:176:30
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by ngekoding** [comment]
Langsung muncul seperti itu atau beberapa waktu setelah ready?

**Comment by rudipratm** [comment]
Pesan error ini muncul ketika saya mengirim pesan. Jadi saat tidak lakukan apa-apa, server normal dan bisa login (scan qr).

**Comment by ngekoding** [comment]
Kalau dari issue ini https://github.com/pedroslopez/whatsapp-web.js/issues/1313 kasusnya sudah lama dan sudah diperbaiki di versi yang baru.

Coba dihapus dulu folder .wwebjs_auth, kemudian jalankan ulang.

**Comment by rudipratm** [comment]
### Problem Solved

Langkah yang saya lakukan:
1. Matikan server (whatsapp-api) yang berjalan
2. Jalankan command `npm update whatsapp-web.js`
3. Hapus directory `.wwebjs_auth`
4. Jalankan ulang server whatsapp-api
