### ISSUE TITLE
Cannot read properties of undefined (reading 'QueryExist')

### ISSUE THREAD

**Issue by abdulaziz1999** [ngekoding/whatsapp-api-tutorial#228]
/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'QueryExist')
    at __puppeteer_evaluation_script__:2:47
    at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.getNumberId (/app/node_modules/whatsapp-web.js/src/Client.js:951:16)
    at async Client.isRegisteredUser (/app/node_modules/whatsapp-web.js/src/Client.js:937:24)
    at async /app/app.js:217:30

**Comment by rogers-dwiputra** [comment]
Problemnya ada update versi dari whatsapp web, https://github.com/pedroslopez/whatsapp-web.js/issues/1576
