### ISSUE TITLE
whatsapp APi stop running

### ISSUE THREAD

**Issue by abdulaziz1999** [ngekoding/whatsapp-api-tutorial#238]
/app/helpers/formatter.js:3
  let formatted = number.replace(/\D/g, '');
                         ^

TypeError: Cannot read properties of null (reading 'replace')
    at phoneNumberFormatter (/app/helpers/formatter.js:3:26)
    at /app/app.js:201:18
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at /app/node_modules/express-fileupload/lib/index.js:35:14

**Comment by ngekoding** [comment]
Dari pesan error itu berarti nomor telepon yang diberikan kosong (null).

**Comment by abdulaziz1999** [comment]
tinggal ditambahakan validasi if nomor null ya

**Comment by ngekoding** [comment]
Ya, bisa seperti itu.
