### ISSUE TITLE
WhatsApp Multi Device

### ISSUE THREAD

**Issue by ccmks** [ngekoding/whatsapp-api-tutorial#242]
Untuk WhatsApp GW yg multi device, dimana saya bisa melihat errornya. Karena, saya punya 3 nomor WA, yg dimana hanya 1 nomor yg tidak bisa kirim pesan, sementara kedua lainnya bisa.

Terima kasih

**Comment by ngekoding** [comment]
Seharusnya ada pesan error pada response pengiriman pesannya.

**Comment by ccmks** [comment]
Errornya connection timeout

**Comment by ccmks** [comment]
Kalau bisa saya pengen liat error di WA Gateway, cuma tidak tahu di mana liatnya

**Comment by ccmks** [comment]
Ini masih belum terjawab. Dimana bisa liat error log dalam WAGW kalau multi device? Klo single device, bisa langsung kelihatan di console SSH, tp klo multi device tidak bisa liat. Dimana liatnya? Krn ini ada 1 nomor yg terus connection timeout, sementara nomor lain tidak

**Comment by ccmks** [comment]
Sdh, ketemu. Sy pakai PM2 logs

Cuma kasusnya seperti ini:

0|app      |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|app      | Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
0|app      |     at CDPSession.send (/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:218:35)
0|app      |     at ExecutionContext._evaluateInternal (/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50)
0|app      |     at ExecutionContext.evaluate (/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27)
0|app      |     at DOMWorld.evaluate (/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24)
0|app      |     at runMicrotasks (<anonymous>)


Apa kira2 solusinya?

**Comment by mdestafadilah** [comment]
> Sdh, ketemu. Sy pakai PM2 logs
> 
> Cuma kasusnya seperti ini:
> 
> 0|app | at processTicksAndRejections (node:internal/process/task_queues:96:5) 0|app | Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed. 0|app | at CDPSession.send (/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:218:35) 0|app | at ExecutionContext._evaluateInternal (/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:204:50) 0|app | at ExecutionContext.evaluate (/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:27) 0|app | at DOMWorld.evaluate (/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:97:24) 0|app | at runMicrotasks ()
> 
> Apa kira2 solusinya?

coba lakukan instlasi library tambahan 

```bash
$ sudo apt-get install chromium-browser
$ sudo apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libgbm-dev
```

sumber: https://github.com/pedroslopez/whatsapp-web.js/issues/972#issuecomment-1083028648
