### ISSUE TITLE
can't running on docker container

### ISSUE THREAD

**Issue by dulumina** [ngekoding/whatsapp-api-tutorial#245]
saya coba kembangkan repo ini, dan ingin menjalankannnya menggunakan **docker** tapi sepertinya ada masalah dengan **puppeterr** yang digunakan oleh **whatsapp-web.js**

berikut pesan error dari docker logs :
```
Sessions file created successfully.
App running on *: 8000
Create session: test-user
Creating session: test-user
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).
    at ChromeLauncher.launch (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:105:23)
    at PuppeteerNode.launch (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js:125:31)
    at Client.initialize (/usr/src/app/node_modules/whatsapp-web.js/src/Client.js:100:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

semoga ada yang bisa mencobanya, dan mau berbagi.

**Comment by difaagung2410** [comment]
`FROM node:16
WORKDIR /home/node/app
COPY package*.json ./
RUN npm install
RUN npm i -g nodemon
COPY --chown=node:node . .
EXPOSE 3000
RUN apt-get update
RUN apt-get install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libatk-bridge2.0-0 libgbm-dev
CMD ["nodemon","app.js"]`

Coba Dockerfilenya pake ini bro
