### ISSUE TITLE
Tidak bisa kirim pesan WA Bisnis

### ISSUE THREAD

**Issue by ccmks** [ngekoding/whatsapp-api-tutorial#261]
Dapat error seperti ini:

0|app  | Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'createWid')
0|app  |     at __puppeteer_evaluation_script__:2:49
0|app  |     at ExecutionContext._evaluateInternal (/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
0|app  |     at runMicrotasks (<anonymous>)
0|app  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|app  |     at async ExecutionContext.evaluate (/wa/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
0|app  |     at async Client.getNumberId (/wa/node_modules/whatsapp-web.js/src/Client.js:1044:16)
0|app  |     at async Client.isRegisteredUser (/wa/node_modules/whatsapp-web.js/src/Client.js:1030:24)
0|app  |     at async /wa/app.js:215:30

Sudah update WA bisnis paling terbaru, msh sj spt ini. Kenapa ya?

Terima kasih

**Comment by ccmks** [comment]
Masalah di Linux dan Windows juga
