### ISSUE TITLE
Error: Evaluation failed: Error: user must have an id or a phone

### ISSUE THREAD

**Issue by nuz-faiz** [ngekoding/whatsapp-api-tutorial#269]
Error: Evaluation failed: Error: user must have an id or a phone
    at t.USyncUser.validate (https://web.whatsapp.com/app.77ee8aa7a4c593101105.js:50:58574)
    at https://web.whatsapp.com/app.77ee8aa7a4c593101105.js:50:50786
    at Array.filter (<anonymous>)
    at t.USyncQuery._buildStanza (https://web.whatsapp.com/app.77ee8aa7a4c593101105.js:50:50718)
    at https://web.whatsapp.com/app.77ee8aa7a4c593101105.js:50:51431
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~app.58a51d93a250f83ab555.js:2:66483)
    at s (https://web.whatsapp.com/vendor1~app.58a51d93a250f83ab555.js:2:66694)
    at https://web.whatsapp.com/vendor1~app.58a51d93a250f83ab555.js:2:66753
    at Y (https://web.whatsapp.com/app.77ee8aa7a4c593101105.js:40:119783)
    at ExecutionContext._evaluateInternal (D:\wa\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (D:\wa\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.getNumberId (D:\wa\node_modules\whatsapp-web.js\src\Client.js:1044:16)
    at async Client.isRegisteredUser (D:\wa\node_modules\whatsapp-web.js\src\Client.js:1030:24)
    at async checkRegisteredNumber (D:\wa\app.js:154:24)
    at async D:\wa\app.js:174:30

**Comment by nuz-faiz** [comment]
Mohon Bantuan / Pencerahanya 
@ngekoding

**Comment by tyasa2000** [comment]
delete folder whatsapp-web.js and then npm i whatsapp-web.js
node app.js

**Comment by nuz-faiz** [comment]
> delete folder whatsapp-web.js and then npm i whatsapp-web.js node app.js

thank you very much
