### ISSUE TITLE
I am getting the following error when trying to send a message

### ISSUE THREAD

**Issue by thiagociavolela** [ngekoding/whatsapp-api-tutorial#284]
anyone experiencing the same problem?

App running on *: 8002
(node:88484) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')
    at __puppeteer_evaluation_script__:2:38
    at ExecutionContext._evaluateInternal (/www/wwwroot/brgamescs.com/api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/www/wwwroot/brgamescs.com/api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.getNumberId (/www/wwwroot/brgamescs.com/api/node_modules/whatsapp-web.js/src/Client.js:1044:16)
    at async Client.isRegisteredUser (/www/wwwroot/brgamescs.com/api/node_modules/whatsapp-web.js/src/Client.js:1030:24)
    at async checkRegisteredNumber (/www/wwwroot/brgamescs.com/api/app.js:159:24)
    at async /www/wwwroot/brgamescs.com/api/app.js:184:30
(Use `node --trace-warnings ...` to show where the warning was created)
(node:88484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:88484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nelson8013** [comment]
I had this issue. I fixed it by using the latest version of whatsAppJs 1.19.4

Try it, it should work
