### ISSUE TITLE
Unsupported Protocol Version 

### ISSUE THREAD

**Issue by natsirasrafi** [ngekoding/whatsapp-api-tutorial#49]
Unsupported Protocol Version ini socket windows

**Comment by ngekoding** [comment]
Bisa disertakan screenshotny?

**Comment by natsirasrafi** [comment]
https://ibb.co/WfHZqYk 
|

**Comment by natsirasrafi** [comment]
App running on *: 8000
(node:7948) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector `canvas` failed: timeout 45000ms exceeded
    at new WaitTask (C:\Users\Z85\Downloads\whatsapp-api-tutorial-master\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:505:34)
    at DOMWorld.waitForSelectorInPage (C:\Users\Z85\Downloads\whatsapp-api-tutorial-master\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:416:26)
    at Object.internalHandler.waitFor (C:\Users\Z85\Downloads\whatsapp-api-tutorial-master\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (C:\Users\Z85\Downloads\whatsapp-api-tutorial-master\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:312:29)
    at Frame.waitForSelector (C:\Users\Z85\Downloads\whatsapp-api-tutorial-master\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:842:51)
    at Page.waitForSelector (C:\Users\Z85\Downloads\whatsapp-api-tutorial-master\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1285:33)
    at getQrCode (C:\Users\Z85\Downloads\whatsapp-api-tutorial-master\node_modules\whatsapp-web.js\src\Client.js:128:28)    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7948) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Express-file-upload: Request is not eligible for file upload!

**Comment by ngekoding** [comment]
Sepertinya masalah di Puppeteernya, itu sudah pakai versi whatsapp-web.js terbaru?

**Comment by natsirasrafi** [comment]
Gatau, ya cuma pakai src dari sini

**Comment by natsirasrafi** [comment]
{code: 5, message: "Unsupported protocol version"} 

saya baru install di vps tapi muncul error seperti itu di console ?

**Comment by ibnudirsan** [comment]
[whatsapp-web.js 1.15.3]
[nodejs v16.13.0]

"UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector canvas failed: timeout 45000ms exceeded".
saya juga mendapatkan error sama persis seperti itu..
ini yang terjadi pada saya..
setiap Auth scan QRCode berhasil, kan create file session.
nah ketika kita coba keluar dari session lewat handphone,
kan file session nya di delete.
ketika kita coba buat session lagi dengan cara scan QRCode dengan ID yang sama,
maka di logs selalu create QRCode secara terus menerus walaupun sudah berhasil scan QRCode untuk ke dua kali nya dengan ID yang sama.

sampai saat ini belum tau fix bug nya dari sisi codingan.

cuma saya coba untuk restat server dalam status file session masih ada dan bernilai true.
setelah server UP,
saya coba masukan ID lagi di Front End nya (HTML nya).
tanpa ada scan QRCode.
saya liat log nya stabil.
dan bisa kirim wa.

Note : 
cuma saya dapat error ini :
{"httpcode":401,"error":"true","data":{"message":"Authentication is not correct."}}{"httpcode":401,"error":"true","data":{"message":"Authentication is not correct."}}{"httpcode":401,"error":"true","data":{"message":"Authentication is not correct."}}

kondisi masih bisa kirim wa walaupun ada log seperti itu..
