### ISSUE TITLE
Setelah npm run start berjalan lancar, beberapa jam kemudian muncul error

### ISSUE THREAD

**Issue by falenas93** [ngekoding/whatsapp-api-tutorial#63]
pertama setelah saya jalankan npm run start tidak ada kendala, tapi beberapa jam kemudian muncul error seperti ini

(node:3383) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'canSend' of undefined
    at Object.canReply (https://web.whatsapp.com/bootstrap_qr.9a2bebd8f0c9b5068d2c.js:16:339323)
    at Object.window.WWebJS.sendMessage (__puppeteer_evaluation_script__:41:31)
    at __puppeteer_evaluation_script__:9:45
    at ExecutionContext._evaluateInternal (/var/www/html/android/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3383) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3383) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

setelah error ini, whatsapp api tidak bisa mengirim wa lg, dan solusinya sementara ini cuman restart pc, jalankan npm, scan barcode lg..

minta pencarahannya kak, trims...

**Comment by rizalfaozi** [comment]
sama ni aku juga

**Comment by ngekoding** [comment]
Kebetulan saya belum pernah mengalami masalah itu, akan tetapi dicoba perhatikan beberapa hal berikut.

- Gunakan Node.js versi 14
- Gunakan whatsapp-web.js versi terbaru

+++

@palenas kenapa perlu restart PC? Apakah komputernya hang?
