### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AdemirShark** [ngekoding/whatsapp-api-tutorial#75]
`2021-07-13T19:08:59.439427+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: webpackChunkbuild is not defined
2021-07-13T19:08:59.439466+00:00 app[web.1]:     at fillModuleArray (eval at <anonymous> (:2:5), <anonymous>:6:5)
2021-07-13T19:08:59.439466+00:00 app[web.1]:     at moduleRaid (eval at <anonymous> (:2:5), <anonymous>:15:3)
2021-07-13T19:08:59.439468+00:00 app[web.1]:     at __puppeteer_evaluation_script__:4:17
2021-07-13T19:08:59.439469+00:00 app[web.1]:     at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
2021-07-13T19:08:59.439469+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-07-13T19:08:59.439470+00:00 app[web.1]:     at async ExecutionContext.evaluate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
2021-07-13T19:08:59.439471+00:00 app[web.1]:     at async Client.initialize (/app/node_modules/whatsapp-web.js/src/Client.js:148:9)
2021-07-13T19:08:59.439712+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2021-07-13T19:08:59.439896+00:00 app[web.1]: (node:21) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by AdemirShark** [comment]
Fixed with NODE 14.17.0 update
