### ISSUE TITLE
Protocol error (Runtime.callFunctionOn): Target closed.

### ISSUE THREAD

**Issue by sangajiputra** [ngekoding/whatsapp-api-tutorial#81]
ketika saya ingin send image malah muncul pesan

Error: Protocol error (Runtime.callFunctionOn): Target closed.

mohon bantu solusinya

**Comment by ahmdaka06** [comment]
how to solve??

**Comment by ngekoding** [comment]
Ada informasi lebih detail?

**Comment by ahmdaka06** [comment]
Alurnya ini mas pas muncul problem itu
Scan > berhasil scan > Kirim pesan success > lalu logout > Scan lagi > berhasil scan > kirim pesan > result error dengan dengan result Protocol error (Runtime.callFunctionOn): Target closed.

**Comment by ngekoding** [comment]
Logout melalui HP?

**Comment by ahmdaka06** [comment]
> Logout melalui HP?

Iya logout via hp mau web htmlnya

**Comment by ahmdaka06** [comment]
![image](https://user-images.githubusercontent.com/61258278/132158114-867b7aef-0067-49e7-b1db-a65941db5809.png)

terkadang errornya begitu mas

**Comment by ngekoding** [comment]
Ini pakai yang multiple device ya?

**Comment by ahmdaka06** [comment]
Iyaa mas barangkali ada solusinya

**Comment by ngekoding** [comment]
Coba IDnya jangan gunakan angka saja, misal: Primary1, dst…

**Comment by ahmdaka06** [comment]
Sama saja mas

**Comment by faiz5758** [comment]
> Error: Protocol error (Runtime.callFunctionOn): Target closed.
> 
> ini terjadi karena apa? mohon bantuan dan solusinya


Kasus sama 

C:\wa\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:217
            this._callbacks.set(id, { resolve, reject, error: new Error(), method });
                                                              ^

Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at C:\wa\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:217:63
    at new Promise (<anonymous>)
    at CDPSession.send (C:\wa\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:216:16)
    at ExecutionContext._evaluateInternal (C:\wa\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluateHandle (C:\wa\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:155:21)
    at WaitTask.rerun (C:\wa\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:536:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
