### ISSUE TITLE
Error : Cannot read property 'replace' of undefined after install express-fileupload (1.2.1)

### ISSUE THREAD

**Issue by aanyudha** [ngekoding/whatsapp-api-tutorial#91]
after install express-fileupload (1.2.1) error showed up. here I attach the error code that may be on formater.js

Express-file-upload: Request is not eligible for file upload!
TypeError: Cannot read property 'replace' of undefined
    at phoneNumberFormatter (C:\nodejs\whatsapp-api\helpers\formatter.js:3:26)
    at C:\nodejs\whatsapp-api\app.js:149:18
    at Layer.handle [as handle_request] (C:\nodejs\whatsapp-api\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\nodejs\whatsapp-api\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\nodejs\whatsapp-api\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\nodejs\whatsapp-api\node_modules\express\lib\router\layer.js:95:5)
    at C:\nodejs\whatsapp-api\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\nodejs\whatsapp-api\node_modules\express\lib\router\index.js:335:12)
    at next (C:\nodejs\whatsapp-api\node_modules\express\lib\router\index.js:275:10)
    at C:\nodejs\whatsapp-api\node_modules\express-fileupload\lib\index.js:34:14

**Comment by ngekoding** [comment]
Let me ask first, do you use this code directly or follow the tutorials?

**Comment by aanyudha** [comment]
I follow your tutorials for this upload.

I use it on another PC its works fine. then suddenly, i back to my PC that contain the error, it's work fine either. still didn't know what caused the error. but right know it working fine.

on both PC I use the same version of NPM and Node
- npm 6.14.12
- node 12.22.1

Thank you
